"""Add notes column to Appoint

Revision ID: b408e6ee4e4b
Revises: 8120fa54157f
Create Date: 2024-11-08 07:03:50.649298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b408e6ee4e4b'
down_revision = '8120fa54157f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appoint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appoint', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
